# Generated by Django 4.0 on 2021-12-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20, verbose_name='用户名')),
                ('pname', models.CharField(blank=True, choices=[('杂物', '杂物'), ('脏污', '脏污'), ('行人扶梯一米栏', '行人扶梯一米栏'), ('红绿灯', '红绿灯'), ('S线数据', 'S线数据'), ('室内可通行', '室内可通行'), ('75车库车辆行人', '75车库车辆行人'), ('111室外车辆行人', '111室外车辆行人')], max_length=100, null=True, verbose_name='项目类型')),
                ('waibao', models.CharField(blank=True, choices=[('是', '是'), ('否', '否')], max_length=10, null=True, verbose_name='是否外包任务')),
                ('task_id', models.BigIntegerField(blank=True, null=True, verbose_name='任务ID')),
                ('dtime', models.CharField(max_length=20, verbose_name='当天日期')),
                ('kinds', models.CharField(choices=[('标注', '标注'), ('审核', '审核'), ('筛选', '筛选')], max_length=20, verbose_name='任务类型')),
                ('pnums', models.IntegerField(blank=True, null=True, verbose_name='图片数量')),
                ('knums', models.IntegerField(blank=True, null=True, verbose_name='框数')),
                ('ptimes', models.FloatField(verbose_name='工时')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uname', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('pword', models.CharField(max_length=128)),
                ('power', models.IntegerField(default=2, max_length=1)),
            ],
        ),
    ]
