# Generated by Django 3.2.15 on 2023-01-12 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '项目列表'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name_plural': 'GS任务列表'},
        ),
        migrations.AlterModelOptions(
            name='tkinds',
            options={'verbose_name_plural': '任务类型列表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '用户列表'},
        ),
        migrations.AlterModelOptions(
            name='waibao',
            options={'verbose_name_plural': '供应商数据列表'},
        ),
        migrations.AlterModelOptions(
            name='waibaos',
            options={'verbose_name_plural': '供应商列表'},
        ),
        migrations.AlterField(
            model_name='project',
            name='pname',
            field=models.CharField(blank=True, max_length=125, unique=True, verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='task',
            name='kinds',
            field=models.CharField(max_length=20, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='waibao',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='数据标注方'),
        ),
        migrations.AlterField(
            model_name='waibao',
            name='get_data_time',
            field=models.CharField(max_length=20, null=True, verbose_name='收到标注结果时间'),
        ),
        migrations.AlterField(
            model_name='waibao',
            name='knums',
            field=models.IntegerField(null=True, verbose_name='标注数量'),
        ),
        migrations.AlterField(
            model_name='waibao',
            name='pname',
            field=models.CharField(blank=True, max_length=128, verbose_name='项目名字'),
        ),
        migrations.AlterField(
            model_name='waibao',
            name='pnums',
            field=models.IntegerField(blank=True, verbose_name='送标样本数量'),
        ),
        migrations.AlterField(
            model_name='waibao',
            name='settlement_method',
            field=models.CharField(max_length=256, null=True, verbose_name='结算方式'),
        ),
        migrations.AlterField(
            model_name='waibao',
            name='unit_price',
            field=models.FloatField(null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='waibaos',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='外包1名字'),
        ),
        migrations.CreateModel(
            name='TaskSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(verbose_name='创建时间')),
                ('knums', models.JSONField(verbose_name='框数')),
                ('money', models.JSONField(verbose_name='总价')),
                ('proname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ess.project', to_field='pname', verbose_name='项目名字')),
                ('wb_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ess.waibaos', to_field='name', verbose_name='供应商名字')),
            ],
            options={
                'verbose_name_plural': '图表统计表',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(auto_created=True, default='1999-01-01')),
                ('send_data_time', models.DateField(default='1999-01-01', verbose_name='送标时间')),
                ('pnums', models.IntegerField(blank=True, verbose_name='送标样本数量')),
                ('data_source', models.CharField(choices=[('人工采集', '人工采集'), ('数据回流', '数据回流'), ('未知', '未知')], default='未知', max_length=256, verbose_name='数据来源')),
                ('scene', models.TextField(default='未知', verbose_name='场景分布')),
                ('send_reason', models.TextField(default='未知', verbose_name='送标原因')),
                ('key_frame_extracted_methods', models.TextField(default='未知', verbose_name='关键帧抽取方式')),
                ('begin_check_data_time', models.DateField(null=True, verbose_name='开始验收时间')),
                ('last_check_data_time', models.DateField(null=True, verbose_name='结束验收时间')),
                ('get_data_time', models.DateField(max_length=20, null=True, verbose_name='收到标注结果时间')),
                ('ann_meta_data', models.JSONField(null=True, verbose_name='准确率,框数,结算方式,单价')),
                ('total_money', models.FloatField(null=True, verbose_name='总金钱')),
                ('proname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ess.project', to_field='pname', verbose_name='项目名字')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='研发')),
                ('wb_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ess.waibaos', to_field='name', verbose_name='供应商')),
            ],
            options={
                'verbose_name_plural': '供应商数据列表新',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateField(verbose_name='创建时间')),
                ('knums', models.JSONField(verbose_name='框数')),
                ('money', models.JSONField(verbose_name='总价')),
                ('proname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ess.project', to_field='pname', verbose_name='项目名字')),
            ],
            options={
                'verbose_name_plural': '图表统计表',
            },
        ),
    ]
