# Generated by Django 3.2.15 on 2023-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0003_supplier_send_data_batch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Waibao',
        ),
        migrations.AddField(
            model_name='supplier',
            name='ann_field_flag',
            field=models.CharField(default=None, max_length=128, verbose_name='首次标注or返修标注'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ann_meta_data',
            field=models.JSONField(blank=True, null=True, verbose_name='准确率,框数,结算方式,单价'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='begin_check_data_time',
            field=models.DateField(blank=True, null=True, verbose_name='开始验收时间'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='get_data_time',
            field=models.DateField(blank=True, max_length=20, null=True, verbose_name='收到标注结果时间'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_check_data_time',
            field=models.DateField(blank=True, null=True, verbose_name='结束验收时间'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='total_money',
            field=models.FloatField(blank=True, null=True, verbose_name='总金钱'),
        ),
        migrations.AlterField(
            model_name='waibaos',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='外包名字'),
        ),
    ]
