# Generated by Django 3.2.15 on 2023-01-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0004_auto_20230116_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='部门'),
        ),
    ]
