# Generated by Django 3.2.14 on 2023-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0006_auto_20230214_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='anno_task_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='工具链标注任务ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='ann_field_flag',
            field=models.CharField(blank=True, choices=[('首次标注', '首次标注'), ('返修标注', '返修标注')], default=None, max_length=128, verbose_name='首次标注or返修标注'),
        ),
    ]
