name: Django CI

on:
  push:
    branches: [ "feature/env" ]
  pull_request:
    branches: [ "feature/env" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    services:
      db:
        image: mysql
        env:
          POSTGRES_DB: myess
          POSTGRES_USER: root
          POSTGRES_PASSWORD: 200805
        ports:
          - 3306:3306
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r myess/requirements.txt
    - name: Run Tests
      run: |
        python myess/manage.py runserver 8080
